void HotPink()    {  displaySolid(HOT_PINK);  }
void DarkRed()    {  displaySolid(DARK_RED);  }
void Red()        {  displaySolid(RED);       }
void RedOrange()  {  displaySolid(RED_ORNG);  }
void Orange()     {  displaySolid(ORANGE);    }
void Gold()       {  displaySolid(GOLD);      }
void Yellow()     {  displaySolid(YELLOW);    }
void LawnGreen()  {  displaySolid(LAWN_GRN);  }
void Lime()       {  displaySolid(LIME);      }
void DarkGreen()  {  displaySolid(DARK_GRN);  }
void Green()      {  displaySolid(GREEN);     }
void BlueGreen()  {  displaySolid(BLUE_GRN);  }
void Aqua()       {  displaySolid(AQUA);      }
void SkyBlue()    {  displaySolid(SKYBLUE);   }
void DarkBlue()   {  displaySolid(DARK_BLU);  }
void Blue()       {  displaySolid(BLUE);      }
void BlueViolet() {  displaySolid(B_VIOLET);  }
void Violet()     {  displaySolid(VIOLET);    }
void White()      {  displaySolid(WHITE);     }
void Gray()       {  displaySolid(GRAY);      }
void DarkGray()   {  displaySolid(DARKGRAY);  }
void Black()      {  displaySolid(BLACK);     }
